### ISSUE TITLE
Throws error!

### ISSUE THREAD

**Issue by post2web** [jupyter-incubator/dashboards_server#271]
I just installed the dashboards-server as so:
`sudo npm install -g jupyter-dashboards-server`
It gives me error when I try to use it. Here is the output:
```
evo projects/ : jupyter-dashboards-server --help
module.js:338
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/jupyter-dashboards-server/app.js:11:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```

Here is the output I got from the npm install:
```
evo projects/ : sudo npm install -g jupyter-dashboards-server
npm WARN engine jupyter-dashboards-server@0.7.0: wanted: {"node":"5.10.0"} (current: {"node":"4.1.2","npm":"2.14.4"})
npm WARN peerDependencies The peer dependency phosphor-disposable@^1.0.5 included from jupyter-js-services will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency phosphor-signaling@^1.2.0 included from jupyter-js-services will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> websocket@1.0.23 install /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> phosphor-panel@1.0.0-rc.1 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/jupyter-js-ui/node_modules/phosphor-panel
> npm dedupe

-
> phosphor-dragdrop@0.9.1 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/jupyter-js-ui/node_modules/phosphor-dragdrop
> npm dedupe


> phosphor-menus@1.0.0-rc.1 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/jupyter-js-ui/node_modules/phosphor-menus
> npm dedupe


> phosphor-widget@1.0.0-rc.1 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/jupyter-js-notebook/node_modules/phosphor-widget
> npm dedupe


> phosphor-widget@1.0.0-rc.1 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/jupyter-js-ui/node_modules/phosphor-widget
> npm dedupe


> phosphor-panel@1.0.0-rc.1 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/jupyter-js-notebook/node_modules/phosphor-panel
> npm dedupe


> jupyter-js-ui@0.11.2 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/jupyter-js-ui
> npm dedupe


> jupyter-js-notebook@0.19.1 postinstall /usr/local/lib/node_modules/jupyter-dashboards-server/node_modules/jupyter-js-notebook
> npm dedupe

/usr/local/bin/jupyter-dashboards-server -> /usr/local/lib/node_modules/jupyter-dashboards-server/bin/jupyter-dashboards-server
jupyter-dashboards-server@0.7.0 /usr/local/lib/node_modules/jupyter-dashboards-server
├── ansi-parser@3.2.3
├── url-join@0.0.1
├── connect-flash@0.1.1
├── connect-ensure-login@0.1.1
├── es6-promise@3.2.1
├── requirejs@2.2.0
├── cookie-parser@1.4.3 (cookie-signature@1.0.6, cookie@0.3.1)
├── serve-favicon@2.3.0 (etag@1.7.0, fresh@0.3.0, parseurl@1.3.1, ms@0.7.1)
├── passport-local@1.0.0 (passport-strategy@1.0.0)
├── passport@0.3.2 (pause@0.0.1, passport-strategy@1.0.0)
├── http-proxy@1.14.0 (eventemitter3@1.2.0, requires-port@1.0.0)
├── tmp@0.0.28 (os-tmpdir@1.0.1)
├── morgan@1.7.0 (basic-auth@1.0.4, on-headers@1.0.1, depd@1.1.0, debug@2.2.0, on-finished@2.3.0)
├── font-awesome@4.6.3
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, klaw@1.3.0, jsonfile@2.3.1, graceful-fs@4.1.4)
├── cookie-session@1.2.0 (on-headers@1.0.1, debug@2.2.0, cookies@0.5.0)
├── commonmark@0.25.1 (string.prototype.repeat@0.2.0, mdurl@1.0.1, entities@1.1.1, minimist@1.2.0)
├── hjson@1.8.4
├── body-parser@1.15.2 (content-type@1.0.2, bytes@2.4.0, depd@1.1.0, qs@6.2.0, on-finished@2.3.0, raw-body@2.1.7, http-errors@1.5.0, debug@2.2.0, iconv-lite@0.4.13, type-is@1.6.13)
├── extract-zip@1.5.0 (debug@0.7.4, yauzl@2.4.1, mkdirp@0.5.0, concat-stream@1.5.0)
├── express@4.14.0 (escape-html@1.0.3, array-flatten@1.1.1, cookie-signature@1.0.6, utils-merge@1.0.0, content-type@1.0.2, methods@1.1.2, merge-descriptors@1.0.1, encodeurl@1.0.1, etag@1.7.0, fresh@0.3.0, parseurl@1.3.1, cookie@0.3.1, range-parser@1.2.0, serve-static@1.11.1, vary@1.1.0, content-disposition@0.5.1, path-to-regexp@0.1.7, depd@1.1.0, qs@6.2.0, on-finished@2.3.0, finalhandler@0.5.0, debug@2.2.0, proxy-addr@1.1.2, type-is@1.6.13, accepts@1.3.3, send@0.14.1)
├── rimraf@2.5.4 (glob@7.0.5)
├── phosphor-disposable@1.0.5
├── phosphor-signaling@1.2.0
├── jupyter-js-services@0.10.5 (phosphor-signaling@1.2.0, phosphor-disposable@1.0.5, jupyter-js-utils@0.4.0)
├── busboy@0.2.13 (readable-stream@1.1.14, dicer@0.2.5)
├── bootstrap@3.3.6
├── nconf@0.8.4 (ini@1.3.4, secure-keys@1.0.0, async@1.5.2, yargs@3.32.0)
├── request@2.74.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── websocket@1.0.23 (yaeti@0.0.4, typedarray-to-buffer@3.1.2, debug@2.2.0, nan@2.4.0)
├── jupyter-js-widgets@1.2.0 (underscore@1.8.3, backbone@1.2.0, semver@5.3.0, d3-format@0.5.1, scriptjs@2.5.8, jquery@2.2.4, lolex@1.5.0, jquery-ui@1.10.5)
├── express-handlebars@3.0.0 (graceful-fs@4.1.4, glob@6.0.4, promise@7.1.1, object.assign@4.0.4, handlebars@4.0.5)
├── jupyter-js-ui@0.11.2 (phosphor-arrays@1.0.6, term.js@0.0.7, marked@0.3.5, ansi_up@1.3.0, phosphor-properties@2.0.0, phosphor-domutil@1.2.0, backbone@1.3.3, jupyter-js-utils@0.4.0, phosphor-messaging@1.0.6, phosphor-disposable@1.0.5, phosphor-signaling@1.2.0, jupyter-js-services@0.9.2, codemirror@5.17.0, moment@2.14.1, phosphor-panel@1.0.0-rc.1, jupyter-js-widgets@0.0.17, phosphor-dragdrop@0.9.1, phosphor-menus@1.0.0-rc.1, phosphor-widget@1.0.0-rc.1)
└── jupyter-js-notebook@0.19.1 (phosphor-disposable@1.0.5, phosphor-properties@2.0.0, phosphor-signaling@1.2.0, sanitizer@0.1.3, diff-match-patch@1.0.0, marked@0.3.5, phosphor-observablelist@1.0.0-beta, jupyter-js-services@0.9.2, jupyter-js-utils@0.4.0, file-loader@0.8.5, codemirror@5.17.0, phosphor-widget@1.0.0-rc.1, phosphor-panel@1.0.0-rc.1)
```

**Comment by parente** [comment]
Output looks ok. We probably have a regression in the published package. Does it only fail when you pass the help flag?

**Comment by post2web** [comment]
It does fail the same way with any tag or when I execute jupyter-dashboards-server just by it self

**Comment by parente** [comment]
I just tried installing on my Mac running Node v5.5.0 and npm v3.5.3 and hit no issues.

In your log output, I just noticed:

```
npm WARN engine jupyter-dashboards-server@0.7.0: wanted: {"node":"5.10.0"} (current: {"node":"4.1.2","npm":"2.14.4"})
```

We minimally support Node 5.5 and npm 3.5.3. (I think these are in the README.) You probably need to upgrade.

**Comment by post2web** [comment]
Everything works after update to node v6.3.1
